/** The words the casual games' own pages say, in one place (the games' names and rules are `lib/casual/casual.constants.ts`). */
export const CASUAL_COPY = {
  card: "Casual game",
  never: "Unrated, worth no points, kept only in this browser.",
  setUpTitle: "Choose a level",
  setUpKanji: "段階",
  start: (level: number, story: boolean) => `Start ${story ? "story" : "level"} ${level} →`,
  levelWord: (story: boolean) => (story ? "Story" : "Level"),
  won: "Won",
  going: "In progress",
  fresh: "Not yet played",
  wonOf: (won: number, levels: number, story: boolean) => `${won} of ${levels} ${story ? "stories" : "levels"} won`,
  resume: "Continue →",
  continueLevel: (level: number, story: boolean) => `Continue ${story ? "story" : "level"} ${level} →`,
  about: "About this game",
  /** The result panel under the board. */
  wonTitle: (level: number, story: boolean) => `${story ? "Story" : "Level"} ${level} won`,
  lostTitle: "Not this time",
  gaveUpTitle: "You gave up",
  gaveUpText: (level: number, story: boolean) => `${story ? "Story" : "Level"} ${level} is left unsolved. It stays open to try again.`,
  next: "Next level →",
  nextStory: "Next story →",
  again: "Try again",
  playAgain: "Play again",
  idleDetail: "Nothing has moved for a couple of minutes. There is no clock here; the level simply waits.",
  idleKept: "Your levels won are kept in this browser. This one will be here when you come back.",
  allDone: "Every level is won. Play any of them again, or choose another game.",
  levels: "Choose a level",
  restart: "Restart",
  restartKeeps: "Starts this level again.",
  rulesLink: "Rules",
  idle: "Loading the game…",
  board: (game: string, level: number) => `${game}, level ${level}`,
} as const;
