import { describe, expect, it } from "vitest";

import {
  XP_LEVELS,
  XP_LEVEL_COST,
  levelCrossed,
  xpForLevel,
  xpLevelFor,
  xpStanding,
} from "./xpCurve";

/**
 * The curve, asserted rather than trusted.
 *
 * The table in `xpCurve.ts` was generated by `docs/plans/xp/curve.py` and then
 * rounded to fives by hand-adjacent code, which is exactly the situation where
 * a generator's output wants checking instead of believing. Three of these
 * cases would have caught a real fault in UmaKuma's history: a level that cost
 * less than the one before it, a rounding that flattened two neighbours into
 * equality, and a total that had drifted away from the player it was
 * calibrated against.
 */

describe("the shape of the curve", () => {
  it("has one cost per level-up, and summing it gives the true top", () => {
    // Ninety-nine rungs: reaching level 2, then 3, and so on up to level 100.
    // Level 1 is free and there is no level 101, so a hundredth entry would be
    // the price of a rung that does not exist — and it did exist once, and an
    // honest sum of the table read a wrong level for John because of it.
    const sum = XP_LEVEL_COST.reduce((total, cost) => total + cost, 0);
    expect(XP_LEVEL_COST).toHaveLength(XP_LEVELS - 1);
    expect(sum).toBe(999_999);
    expect(sum).toBe(xpForLevel(XP_LEVELS));
  });

  it("costs more at every level than at the one before", () => {
    // The one UmaKuma got wrong twice: a ladder that got EASIER at the moment
    // it was supposed to start biting. Asserted over the whole sequence
    // because rounding to fives can flatten two neighbours into equality.
    for (let index = 1; index < XP_LEVEL_COST.length; index += 1) {
      expect(XP_LEVEL_COST[index], `level ${index + 1} costs more than level ${index}`).toBeGreaterThan(
        XP_LEVEL_COST[index - 1],
      );
    }
  });

  it("prices every level in a number somebody chose", () => {
    // John's rule from UmaKuma: a cost ending in 0 or 5 reads as a decision,
    // where 1,447 reads as a machine's arithmetic.
    // All but one: Level 100's own rung takes the four that make the top exactly
    // 999,999, which is John's number and outranks the rounding. See the header.
    const top = XP_LEVELS - 2;
    XP_LEVEL_COST.forEach((cost, index) => {
      if (index !== top) expect(cost % 5, `the rung into level ${index + 2}`).toBe(0);
    });
    expect(XP_LEVEL_COST[top] % 5).toBe(4);
  });

  it("gets harder after 10, and again after 20, in steps a player can feel", () => {
    // John: "need to get harder after 10, 20 etc". `XP_LEVEL_COST[level - 2]`
    // is the price of reaching `level`, so [8] is level 10, [9] level 11, [18]
    // level 20 and [19] level 21. Setting the parts independently is how UmaKuma
    // once produced a level 10 costing 250 followed by a level 11 costing 83.
    const reach = (level: number) => XP_LEVEL_COST[level - 2];
    for (let level = 3; level <= 10; level += 1) {
      expect(reach(level) - reach(level - 1), `the ramp at ${level}`).toBe(50);
    }
    expect(reach(11)).toBeGreaterThanOrEqual(reach(10) * 1.5);
    expect(reach(21)).toBeGreaterThanOrEqual(reach(20) * 1.2);
  });

  it("keeps steepening, so the last stretch is a climb and not more of the same", () => {
    // A rising rate, asserted as one: the growth from level 99 to 100 is more
    // than twice the growth from 12 to 13, and the last ten levels cost more
    // than two-fifths of the whole ladder.
    const growth = (level: number) => XP_LEVEL_COST[level - 2] / XP_LEVEL_COST[level - 3] - 1;
    expect(growth(100)).toBeGreaterThan(growth(13) * 2);
    expect(xpForLevel(100) - xpForLevel(90)).toBeGreaterThan(xpForLevel(100) * 0.4);
  });

  it("lets the first ten levels come quickly", () => {
    // Under one percent of the ladder. A new member should feel the first
    // few rungs in an afternoon and reach ten inside a fortnight of play.
    expect(xpForLevel(10)).toBeLessThan(xpForLevel(XP_LEVELS) * 0.01);
    expect(xpForLevel(10)).toBe(2250);
  });

  it("reaches Level 100 at exactly 999,999 XP, and Level 100 is the last rung", () => {
    // John: "you need 999,999 to get to the top level". `XP_LEVEL_COST` holds the
    // price of EACH rung; `xpForLevel` is the running total, and it is the running
    // total that must be his number. If this moves, the climb table in
    // XP_DESIGN.md is no longer true and has to be recomputed.
    expect(XP_LEVELS).toBe(100);
    expect(xpForLevel(100)).toBe(999_999);
    expect(xpLevelFor(999_999)).toBe(100);
    expect(xpLevelFor(999_998)).toBe(99);
    // No level 101: more XP stands on the same top rung, and the price of a rung
    // past the top is the top.
    expect(xpLevelFor(5_000_000)).toBe(100);
    expect(xpForLevel(101)).toBe(999_999);
  });
});

describe("what a level costs to stand at", () => {
  it("starts everybody at level 1 for nothing", () => {
    expect(xpForLevel(1)).toBe(0);
    expect(xpLevelFor(0)).toBe(1);
  });

  it("clamps a level outside the ladder rather than reading off the end", () => {
    expect(xpForLevel(0)).toBe(0);
    expect(xpForLevel(-5)).toBe(0);
    expect(xpForLevel(101)).toBe(xpForLevel(XP_LEVELS));
    expect(xpForLevel(10_000)).toBe(xpForLevel(XP_LEVELS));
  });

  it("agrees with itself in both directions at every level", () => {
    // The pair of functions is the whole contract: the XP that reaches a level
    // must read back AS that level, and one point less must not.
    for (let level = 2; level <= XP_LEVELS; level += 1) {
      expect(xpLevelFor(xpForLevel(level)), `exactly enough for ${level}`).toBe(level);
      expect(xpLevelFor(xpForLevel(level) - 1), `one short of ${level}`).toBe(level - 1);
    }
  });

  it("refuses a total that is not a number rather than guessing one", () => {
    expect(xpLevelFor(Number.NaN)).toBe(1);
    expect(xpLevelFor(Number.POSITIVE_INFINITY)).toBe(1);
    expect(xpLevelFor(-100)).toBe(1);
  });
});

describe("the standing a total earns", () => {
  it("reports the way through a level a progress bar draws", () => {
    const floor = xpForLevel(20);
    const span = xpForLevel(21) - floor;
    const standing = xpStanding(floor + Math.floor(span / 2));
    expect(standing.level).toBe(20);
    expect(standing.span).toBe(span);
    expect(standing.into).toBe(Math.floor(span / 2));
    expect(standing.ratio).toBeCloseTo(0.5, 1);
    expect(standing.toNext).toBe(span - Math.floor(span / 2));
  });

  it("says a fresh account is at the bottom and has somewhere to go", () => {
    const standing = xpStanding(0);
    expect(standing.level).toBe(1);
    expect(standing.into).toBe(0);
    expect(standing.toNext).toBe(XP_LEVEL_COST[0]);
    expect(standing.ratio).toBe(0);
  });

  it("has no next level at the top, and says so as a full bar rather than a divide by zero", () => {
    const standing = xpStanding(xpForLevel(XP_LEVELS) + 10_000);
    expect(standing.level).toBe(XP_LEVELS);
    expect(standing.span).toBe(0);
    expect(standing.toNext).toBe(0);
    expect(standing.ratio).toBe(1);
  });
});

describe("whether an award moved somebody's level", () => {
  it("says nothing when it did not", () => {
    expect(levelCrossed(0, 10)).toBeNull();
    expect(levelCrossed(xpForLevel(30), xpForLevel(30) + 5)).toBeNull();
  });

  it("names the level arrived at", () => {
    expect(levelCrossed(xpForLevel(5) - 1, xpForLevel(5))).toEqual({ from: 4, to: 5 });
  });

  it("reports one crossing when a big award carries somebody through several levels", () => {
    // A first game ever, a first game of a variant and a new family come to
    // 450 on one finish, which is several early levels at once. The caller is
    // told where they arrived, and `from` lets it name every rung.
    const crossed = levelCrossed(0, 500);
    expect(crossed).not.toBeNull();
    expect(crossed?.from).toBe(1);
    expect(crossed?.to).toBeGreaterThan(4);
  });

  it("never reports a crossing backwards", () => {
    // Nothing takes XP away today, and if something ever does it must not be
    // reported as a promotion.
    expect(levelCrossed(xpForLevel(40), xpForLevel(10))).toBeNull();
  });
});
