import { describe, expect, it } from "vitest";

import {
  XP_LEVELS,
  XP_LEVEL_COST,
  levelCrossed,
  xpForLevel,
  xpLevelFor,
  xpStanding,
} from "./xpCurve";

/**
 * The curve, asserted rather than trusted.
 *
 * The table in `xpCurve.ts` was generated by `docs/plans/xp/curve.py` and then
 * rounded to fives by hand-adjacent code, which is exactly the situation where
 * a generator's output wants checking instead of believing. Three of these
 * cases would have caught a real fault in UmaKuma's history: a level that cost
 * less than the one before it, a rounding that flattened two neighbours into
 * equality, and a total that had drifted away from the player it was
 * calibrated against.
 */

describe("the shape of the curve", () => {
  it("has one cost per level", () => {
    expect(XP_LEVEL_COST).toHaveLength(XP_LEVELS);
  });

  it("costs more at every level than at the one before", () => {
    // The one UmaKuma got wrong twice: a ladder that got EASIER at the moment
    // it was supposed to start biting. Asserted over the whole sequence
    // because rounding to fives can flatten two neighbours into equality.
    for (let index = 1; index < XP_LEVEL_COST.length; index += 1) {
      expect(XP_LEVEL_COST[index], `level ${index + 1} costs more than level ${index}`).toBeGreaterThan(
        XP_LEVEL_COST[index - 1],
      );
    }
  });

  it("prices every level in a number somebody chose", () => {
    // John's rule from UmaKuma: a cost ending in 0 or 5 reads as a decision,
    // where 1,447 reads as a machine's arithmetic.
    for (const cost of XP_LEVEL_COST) expect(cost % 5).toBe(0);
  });

  it("does not step down at the handoff from the flat ramp", () => {
    // Levels 1-10 are a flat ramp and 11 onward compound. Setting the two
    // independently is how UmaKuma once produced a level 10 costing 250
    // followed by a level 11 costing 83.
    expect(XP_LEVEL_COST[9]).toBe(200);
    expect(XP_LEVEL_COST[10]).toBe(220);
  });

  it("reaches the total the two reference players were solved against", () => {
    // A committed player earns about 21,900 a year, so ~69,000 in three years
    // plus the 3,740 of one-off awards. If this number moves, the claims in
    // XP_DESIGN.md about what a month and a year reach are no longer true and
    // have to be recomputed rather than left standing.
    expect(xpForLevel(XP_LEVELS)).toBe(68155);
  });
});

describe("what a level costs to stand at", () => {
  it("starts everybody at level 1 for nothing", () => {
    expect(xpForLevel(1)).toBe(0);
    expect(xpLevelFor(0)).toBe(1);
  });

  it("clamps a level outside the ladder rather than reading off the end", () => {
    expect(xpForLevel(0)).toBe(0);
    expect(xpForLevel(-5)).toBe(0);
    expect(xpForLevel(101)).toBe(xpForLevel(XP_LEVELS));
    expect(xpForLevel(10_000)).toBe(xpForLevel(XP_LEVELS));
  });

  it("agrees with itself in both directions at every level", () => {
    // The pair of functions is the whole contract: the XP that reaches a level
    // must read back AS that level, and one point less must not.
    for (let level = 2; level <= XP_LEVELS; level += 1) {
      expect(xpLevelFor(xpForLevel(level)), `exactly enough for ${level}`).toBe(level);
      expect(xpLevelFor(xpForLevel(level) - 1), `one short of ${level}`).toBe(level - 1);
    }
  });

  it("refuses a total that is not a number rather than guessing one", () => {
    expect(xpLevelFor(Number.NaN)).toBe(1);
    expect(xpLevelFor(Number.POSITIVE_INFINITY)).toBe(1);
    expect(xpLevelFor(-100)).toBe(1);
  });
});

describe("the standing a total earns", () => {
  it("reports the way through a level a progress bar draws", () => {
    const floor = xpForLevel(20);
    const span = xpForLevel(21) - floor;
    const standing = xpStanding(floor + Math.floor(span / 2));
    expect(standing.level).toBe(20);
    expect(standing.span).toBe(span);
    expect(standing.into).toBe(Math.floor(span / 2));
    expect(standing.ratio).toBeCloseTo(0.5, 1);
    expect(standing.toNext).toBe(span - Math.floor(span / 2));
  });

  it("says a fresh account is at the bottom and has somewhere to go", () => {
    const standing = xpStanding(0);
    expect(standing.level).toBe(1);
    expect(standing.into).toBe(0);
    expect(standing.toNext).toBe(XP_LEVEL_COST[0]);
    expect(standing.ratio).toBe(0);
  });

  it("has no next level at the top, and says so as a full bar rather than a divide by zero", () => {
    const standing = xpStanding(xpForLevel(XP_LEVELS) + 10_000);
    expect(standing.level).toBe(XP_LEVELS);
    expect(standing.span).toBe(0);
    expect(standing.toNext).toBe(0);
    expect(standing.ratio).toBe(1);
  });
});

describe("whether an award moved somebody's level", () => {
  it("says nothing when it did not", () => {
    expect(levelCrossed(0, 10)).toBeNull();
    expect(levelCrossed(xpForLevel(30), xpForLevel(30) + 5)).toBeNull();
  });

  it("names the level arrived at", () => {
    expect(levelCrossed(xpForLevel(5) - 1, xpForLevel(5))).toEqual({ from: 4, to: 5 });
  });

  it("reports one crossing when a big award carries somebody through several levels", () => {
    // everyVariantPlayed is 500 XP, which is four early levels at once. The
    // caller is told where they arrived, and `from` lets it name every rung.
    const crossed = levelCrossed(0, 500);
    expect(crossed).not.toBeNull();
    expect(crossed?.from).toBe(1);
    expect(crossed?.to).toBeGreaterThan(4);
  });

  it("never reports a crossing backwards", () => {
    // Nothing takes XP away today, and if something ever does it must not be
    // reported as a promotion.
    expect(levelCrossed(xpForLevel(40), xpForLevel(10))).toBeNull();
  });
});
