import type { LegacyPlayer } from "./legacyPlayers.types";

/**
 * Records kept from before Itsutsu — some from people who never played here
 * ("remembered"), some from live members who did, before this site existed
 * ("elsewhere"). The first is the site's first seeder, the record this whole
 * feature was built to keep. Add more the same way: a slug, a source, and
 * the record as it stood.
 */
export const LEGACY_PLAYERS: LegacyPlayer[] = [
  {
    slug: "chibi",
    name: "Chibi",
    kind: "remembered",
    location: "Canada",
    possessive: "his",
    source: "ItsYourTurn.com",
    joined: "2001-07-27",
    lastActive: "2013-07-30",
    relatedSlugs: ["chibi-goldtoken"],
    summary: [
      {
        class: "Regular games",
        record: { game: "Regular games", won: 2077, lost: 1355, drawn: 8 },
        detailComplete: false,
        detail: [
          { game: "Anti-Backgammon", won: 2, lost: 11, drawn: 0 },
          { game: "Anti-Flipversi", won: 1, lost: 1, drawn: 0 },
          { game: "Backgammon", won: 1149, lost: 730, drawn: 0 },
          { game: "Backgammon Level 2", won: 59, lost: 35, drawn: 0 },
          { game: "Backgammon Level 3", won: 2, lost: 1, drawn: 0 },
          { game: "Backgammon Race", won: 150, lost: 92, drawn: 0 },
          { game: "Backgammon Race Level 2", won: 36, lost: 21, drawn: 0 },
          { game: "Battleboats", won: 1, lost: 2, drawn: 0 },
          { game: "Battleboats Plus", won: 20, lost: 33, drawn: 0 },
          { game: "Casual Backgammon", won: 2, lost: 2, drawn: 0 },
          { game: "Flipversi", won: 239, lost: 133, drawn: 1 },
          { game: "Flipversi 10x10", won: 48, lost: 28, drawn: 1 },
          { game: "Flipversi 6x6", won: 27, lost: 19, drawn: 4 },
          { game: "Go-Moku", won: 0, lost: 2, drawn: 0 },
          { game: "Halma", won: 1, lost: 3, drawn: 0 },
          { game: "Hexversi", won: 8, lost: 10, drawn: 1 },
          { game: "Nackgammon", won: 69, lost: 38, drawn: 0 },
          { game: "Pro Backgammon", won: 229, lost: 178, drawn: 0 },
          { game: "Pro Backgammon Level 2", won: 7, lost: 10, drawn: 1 },
          { game: "Pro Backgammon Race", won: 10, lost: 0, drawn: 0 },
          { game: "Pro Backgammon-9", won: 14, lost: 5, drawn: 0 },
          { game: "Pro Nackgammon", won: 3, lost: 1, drawn: 0 },
        ],
      },
      {
        class: "Tournament games",
        record: { game: "Tournament games", won: 266, lost: 286, drawn: 0 },
        detailComplete: true,
        detail: [
          { game: "Backgammon", won: 9, lost: 15, drawn: 0 },
          { game: "Backgammon Level 2", won: 33, lost: 37, drawn: 0 },
          { game: "Backgammon Level 3", won: 20, lost: 22, drawn: 0 },
          { game: "Backgammon Race", won: 23, lost: 25, drawn: 0 },
          { game: "Backgammon Race Level 2", won: 61, lost: 57, drawn: 0 },
          { game: "Casual Backgammon", won: 8, lost: 10, drawn: 0 },
          { game: "Nackgammon", won: 58, lost: 56, drawn: 0 },
          { game: "Pro Backgammon", won: 16, lost: 14, drawn: 0 },
          { game: "Pro Backgammon Level 2", won: 32, lost: 44, drawn: 0 },
          { game: "Pro Backgammon Race", won: 6, lost: 6, drawn: 0 },
        ],
      },
      {
        class: "Ladder games",
        record: { game: "Ladder games", won: 71, lost: 54, drawn: 1 },
        detailComplete: true,
        detail: [
          { game: "Backgammon", won: 59, lost: 39, drawn: 1 },
          { game: "Pro Backgammon Race", won: 12, lost: 15, drawn: 0 },
        ],
      },
    ],
  },
  {
    slug: "kyokosan",
    name: "Kyokosan",
    kind: "honorary",
    location: "Canada",
    possessive: "her",
    source: "ItsYourTurn.com",
    joined: "2001-07-26",
    lastActive: "2009-09-30",
    summary: [
      {
        class: "Regular games",
        record: { game: "Regular games", won: 2889, lost: 2405, drawn: 34 },
        detailComplete: true,
        detail: [
          { game: "Anti-Flipversi", won: 1, lost: 7, drawn: 0 },
          { game: "Anti-Flipversi 6x6", won: 0, lost: 1, drawn: 0 },
          { game: "Connect 6", won: 15, lost: 9, drawn: 0 },
          { game: "Flipversi", won: 328, lost: 399, drawn: 15 },
          { game: "Flipversi 10x10", won: 43, lost: 68, drawn: 3 },
          { game: "Flipversi 6x6", won: 151, lost: 84, drawn: 7 },
          { game: "Flipversi Blackhole 10x10", won: 0, lost: 1, drawn: 0 },
          { game: "Go-Moku", won: 913, lost: 586, drawn: 9 },
          { game: "Halma", won: 78, lost: 101, drawn: 0 },
          { game: "Halma 10x10", won: 95, lost: 67, drawn: 0 },
          { game: "Keryo Pente", won: 783, lost: 645, drawn: 0 },
          { game: "Pente", won: 478, lost: 423, drawn: 0 },
          { game: "Pro Go-Moku", won: 3, lost: 4, drawn: 0 },
          { game: "Pro Pente", won: 1, lost: 9, drawn: 0 },
          { game: "Stack 4x4", won: 0, lost: 1, drawn: 0 },
        ],
      },
      {
        class: "Tournament games",
        record: { game: "Tournament games", won: 37, lost: 36, drawn: 1 },
        detailComplete: true,
        detail: [
          { game: "Flipversi", won: 18, lost: 18, drawn: 0 },
          { game: "Go-Moku", won: 12, lost: 13, drawn: 1 },
          { game: "Pente", won: 4, lost: 2, drawn: 0 },
          { game: "Pro Go-Moku", won: 3, lost: 3, drawn: 0 },
        ],
      },
    ],
  },
  {
    slug: "incognito",
    name: "Incognito",
    kind: "elsewhere",
    location: "Canada",
    possessive: "his",
    source: "ItsYourTurn.com",
    joined: "2001-05-29",
    lastActive: "2007-04-04",
    note: "Two of the Backgammon losses on record — the only ones — were against his father, Chibi, on 2001-08-17 and 2001-08-18.",
    relatedSlugs: ["jmorris"],
    summary: [
      {
        class: "Regular games",
        record: { game: "Regular games", won: 1533, lost: 164, drawn: 12 },
        detailComplete: true,
        detail: [
          { game: "Anti-Checkers", won: 230, lost: 25, drawn: 0 },
          { game: "Anti-Flipversi", won: 244, lost: 18, drawn: 9 },
          { game: "Backgammon", won: 0, lost: 2, drawn: 0 },
          { game: "Checkers", won: 15, lost: 2, drawn: 0 },
          { game: "Crowded Checkers", won: 5, lost: 1, drawn: 0 },
          { game: "Flipversi", won: 173, lost: 23, drawn: 1 },
          { game: "Flipversi 6x6", won: 21, lost: 6, drawn: 0 },
          { game: "Go-Moku", won: 175, lost: 22, drawn: 2 },
          { game: "Halma", won: 41, lost: 7, drawn: 0 },
          { game: "Halma 10x10", won: 41, lost: 1, drawn: 0 },
          { game: "Keryo Pente", won: 194, lost: 22, drawn: 0 },
          { game: "Pente", won: 165, lost: 20, drawn: 0 },
          { game: "Pro Go-Moku", won: 78, lost: 8, drawn: 0 },
          { game: "Pro Pente", won: 137, lost: 5, drawn: 0 },
          { game: "Stack4", won: 14, lost: 2, drawn: 0 },
        ],
      },
    ],
  },
  {
    slug: "jmorris",
    name: "John Morris",
    kind: "elsewhere",
    location: "Canada",
    possessive: "his",
    source: "GoldToken.com",
    sourceUrl: "https://www.goldtoken.com/games/player?p=66756",
    sourceId: "66756",
    joined: "2011-06-25",
    lastActive: "2026-09-08",
    note: "Reversi here is the same game as Flipversi on ItsYourTurn — one game, two sites' names for it. GoldToken's own rating averaged 1689 across every game; a different scale from Itsutsu's Elo, not converted or compared.",
    relatedSlugs: ["incognito"],
    summary: [
      {
        class: "Friendly games",
        record: { game: "Friendly games", won: 188, lost: 41, drawn: 7 },
        detailComplete: true,
        detail: [
          { game: "Golden Pente", won: 64, lost: 6, drawn: 0 },
          { game: "Pente", won: 82, lost: 14, drawn: 0 },
          { game: "Large Go Moku", won: 23, lost: 3, drawn: 0 },
          {
            game: "Go Moku",
            won: 18,
            lost: 7,
            drawn: 0,
            log: [
              { date: "2020-01-15", opponent: "GROWLINGMAD", result: "won" },
              { date: "2020-01-14", opponent: "GROWLINGMAD", result: "won" },
              { date: "2020-01-07", opponent: "GROWLINGMAD", result: "won" },
              { date: "2019-12-27", opponent: "GROWLINGMAD", result: "won" },
              { date: "2019-12-08", opponent: "curlywolf", result: "lost" },
              { date: "2019-11-26", opponent: "AmberLove", result: "won" },
              { date: "2019-10-21", opponent: "Wild Horse", result: "won" },
              { date: "2019-10-21", opponent: "Wild Horse", result: "won" },
              { date: "2019-10-21", opponent: "JL579", result: "lost" },
              { date: "2019-10-15", opponent: "JL579", result: "lost" },
              { date: "2019-10-04", opponent: "builderbob54", result: "lost" },
              { date: "2019-09-30", opponent: "builderbob54", result: "lost" },
              { date: "2019-09-03", opponent: "AmberLove", result: "lost" },
              { date: "2019-08-22", opponent: "curlywolf", result: "won" },
              { date: "2019-07-23", opponent: "Wild Horse", result: "lost" },
              { date: "2011-09-17", opponent: "asiula", result: "won" },
              { date: "2011-08-31", opponent: "asiula", result: "won" },
              { date: "2011-08-07", opponent: "Kentish Martin", result: "won" },
              { date: "2011-08-05", opponent: "Kentish Martin", result: "won" },
              { date: "2011-08-03", opponent: "BITman", result: "won" },
              { date: "2011-08-03", opponent: "Aspen", result: "won" },
              { date: "2011-07-28", opponent: "Aspen", result: "won" },
              { date: "2011-07-06", opponent: "Aspen", result: "won" },
              { date: "2011-07-04", opponent: "BITman", result: "won" },
              { date: "2011-07-03", opponent: "Aspen", result: "won" },
            ],
          },
          { game: "Backgammon", won: 0, lost: 3, drawn: 2 },
          { game: "Nackgammon", won: 0, lost: 4, drawn: 2 },
          { game: "Small Go Moku", won: 1, lost: 0, drawn: 0 },
          { game: "Long Gammon", won: 0, lost: 2, drawn: 1 },
          { game: "Nackgammon (3 Point)", won: 0, lost: 0, drawn: 1 },
          { game: "Backgammon (3 Point)", won: 0, lost: 0, drawn: 1 },
          { game: "Reversi", won: 0, lost: 2, drawn: 0 },
        ],
      },
    ],
  },
  {
    slug: "chibi-goldtoken",
    name: "Chibi",
    kind: "remembered",
    location: "Canada",
    possessive: "his",
    source: "GoldToken.com",
    sourceUrl: "https://www.goldtoken.com/games/album?id=8686;pid=24612",
    sourceId: "24612",
    joined: "2003-03-13",
    lastActive: "2020-11-10",
    note: "A profile photo he posted, 27 May 2012 — his own reply to a comment on it says it was taken in Japan, a long time before.",
    comments: [
      { text: "That's a beautiful photograph!", by: "Twit-twoo", at: "2013-06-04 12:47" },
      { text: "Great photo! Where was this taken? when? Thanks for sharing!", by: "Nanna K", at: "2014-09-19 20:07" },
      { text: "thank you\ntaken in Japan a long time ago", by: "Chibi", at: "2014-09-19 21:00" },
      { text: "Is this you in the picture?", by: "Churchgoer", at: "2015-02-18 21:45" },
    ],
    relatedSlugs: ["chibi"],
    summary: [
      {
        class: "Friendly games",
        record: { game: "Friendly games", won: 4983, lost: 4434, drawn: 46 },
        detailComplete: true,
        detail: [
          { game: "Long Gammon", won: 272, lost: 166, drawn: 8 },
          { game: "Reversi", won: 1, lost: 3, drawn: 0 },
          { game: "Nackgammon", won: 306, lost: 281, drawn: 5 },
          { game: "Tabula", won: 5, lost: 1, drawn: 0 },
          { game: "Hypergammon", won: 5, lost: 5, drawn: 0 },
          { game: "Backgammon", won: 3721, lost: 3343, drawn: 27 },
          { game: "Inverticade", won: 1, lost: 7, drawn: 0 },
          { game: "GoldFences", won: 13, lost: 67, drawn: 0 },
          { game: "Skat", won: 0, lost: 9, drawn: 0 },
          { game: "Whist", won: 0, lost: 8, drawn: 0 },
          { game: "Nackgammon (5 Point)", won: 10, lost: 11, drawn: 0 },
          { game: "Nackgammon (9 Point)", won: 8, lost: 18, drawn: 0 },
          { game: "Hit&Miss Salvo", won: 0, lost: 1, drawn: 0 },
          { game: "Long Gammon (3 Point)", won: 20, lost: 9, drawn: 0 },
          { game: "Long Gammon (7 Point)", won: 11, lost: 2, drawn: 0 },
          { game: "Salvo", won: 0, lost: 0, drawn: 2 },
          { game: "Backgammon (9 Point)", won: 98, lost: 63, drawn: 2 },
          { game: "Backgammon (5 Point)", won: 146, lost: 99, drawn: 0 },
          { game: "Euro Domination", won: 0, lost: 1, drawn: 0 },
          { game: "Backgammon (3 Point)", won: 249, lost: 251, drawn: 1 },
          { game: "Backgammon (7 Point)", won: 54, lost: 50, drawn: 0 },
          { game: "Long Gammon (5 Point)", won: 14, lost: 5, drawn: 0 },
          { game: "Long Gammon (9 Point)", won: 19, lost: 13, drawn: 0 },
          { game: "Nackgammon (3 Point)", won: 24, lost: 16, drawn: 1 },
          { game: "Hypergammon (5 Point)", won: 1, lost: 1, drawn: 0 },
          { game: "Hypergammon (3 Point)", won: 1, lost: 1, drawn: 0 },
          { game: "Nackgammon (7 Point)", won: 4, lost: 3, drawn: 0 },
        ],
      },
      {
        class: "Tournament games",
        record: { game: "Tournament games", won: 432, lost: 593, drawn: 0 },
        detailComplete: true,
        detail: [
          { game: "Long Gammon", won: 12, lost: 30, drawn: 0 },
          { game: "Nackgammon", won: 78, lost: 92, drawn: 0 },
          { game: "Backgammon", won: 234, lost: 312, drawn: 0 },
          { game: "Nackgammon (5 Point)", won: 12, lost: 9, drawn: 0 },
          { game: "Long Gammon (3 Point)", won: 3, lost: 7, drawn: 0 },
          { game: "Backgammon (9 Point)", won: 2, lost: 18, drawn: 0 },
          { game: "Backgammon (5 Point)", won: 17, lost: 25, drawn: 0 },
          { game: "Backgammon (3 Point)", won: 58, lost: 81, drawn: 0 },
          { game: "Backgammon (7 Point)", won: 6, lost: 9, drawn: 0 },
          { game: "Long Gammon (5 Point)", won: 3, lost: 2, drawn: 0 },
          { game: "Long Gammon (9 Point)", won: 0, lost: 1, drawn: 0 },
          { game: "Nackgammon (3 Point)", won: 6, lost: 6, drawn: 0 },
          { game: "Nackgammon (7 Point)", won: 1, lost: 1, drawn: 0 },
        ],
      },
    ],
  },
];

export function findLegacyPlayer(slug: string): LegacyPlayer | null {
  const key = slug.trim().toLowerCase();
  return LEGACY_PLAYERS.find((player) => player.slug === key) ?? null;
}

/**
 * Every elsewhere record belonging beside a live player's own name — a
 * person can have played on more than one site before Itsutsu existed, so
 * this is a list, not a single match.
 */
export function findLinkedLegacies(liveKey: string): LegacyPlayer[] {
  return LEGACY_PLAYERS.filter((player) => player.kind === "elsewhere" && player.linkedKey === liveKey);
}
