-- AlterTable
ALTER TABLE "Member" ADD COLUMN "awayFrom" TIMESTAMP(3),
ADD COLUMN "awayUntil" TIMESTAMP(3),
ADD COLUMN "awayDaysUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "awayYear" INTEGER NOT NULL DEFAULT 0;
