// Tenka's rules are their own open-source package (github.com/johnmorrisdotca/tenka, installed as @johnmorrisdotca/tenka);
// this module keeps its old address so the site and its browser specs import it unchanged.
export {
  TENKA_ATTACK_DICE,
  TENKA_CARD_KINDS,
  TENKA_DEFEND_DICE,
  TENKA_FEWEST_PLAYERS,
  TENKA_LEAST_REINFORCEMENT,
  TENKA_LENGTHS,
  TENKA_MEDIUM_ROUNDS,
  TENKA_MOST_PLAYERS,
  TENKA_MOVES,
  TENKA_MUST_TRADE_AT,
  TENKA_NAME_MOST,
  TENKA_NEUTRAL,
  TENKA_PHASES,
  TENKA_PLACING,
  TENKA_SHORT_ROUNDS,
  TENKA_STARTING_ARMIES,
  TENKA_TERRITORIES_PER_ARMY,
  TENKA_TERRITORY_CARD_BONUS,
  TENKA_TRADE_STEP,
  TENKA_TRADE_VALUES,
  TENKA_WILD,
  TENKA_WILD_CARDS,
  TENKA_WORLD_ROUNDS,
} from "@johnmorrisdotca/tenka";
