import type { FamousGame } from "./famous.types";

/**
 * The famous games, as their sources record them — generated once from the
 * files in the research folder by a one-off script, and checked move by move
 * by `famous.test.ts`, which replays every one through the engine. Moves are
 * in each family's own notation: Othello squares ("f5"), SGF points for Go
 * ("pd", "--" for a pass). Credits are in `FAMOUS_SOURCES`.
 */
export const FAMOUS_GAMES: readonly FamousGame[] = [
  {
    id: "alphago-leesedol-1",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "Google DeepMind Challenge Match",
    round: "1",
    date: "2016-03-09",
    place: "Four Seasons Hotel, Seoul, Korea",
    black: "Lee Sedol",
    white: "AlphaGo",
    result: "W+R",
    source: "brouwer",
    moves: "qd dd pq dp fc cf ql od ld qc rc pc re of pg og ph id lf oh pi lh kh ke le lg kg kf ne oe jc ic jd ie je jf if jg li mi hf ih mb gd ki mj kk ib ob ml lm nc nb kb lc mm ln kl ll lk jj jl hj hi gj gf ii jh ij mn lo mo lp mp lq mq im qo fq gg cn dn dm fp gp gq fr co en do ep cm dl lr kr rb jb ja mf mh nd qj pj qk pl pk ok rh rl qf ri rf pf qe qh cc bn bm bl bo rg mr po jr kq pn oo qp on pp op qq or pr oq pd qr rr ps rs rn ro qn so cl an ks om ol ci hh hg dr dj bq cq cr bp dq br cp ap ek fi bj bi pb qb sf rd ai ah aj bh gi fj fk oc mc cj al nm pm aq gh fh",
  },
  {
    id: "alphago-leesedol-2",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "Google DeepMind Challenge Match",
    round: "2",
    date: "2016-03-10",
    place: "Four Seasons Hotel, Seoul, Korea",
    black: "AlphaGo",
    white: "Lee Sedol",
    result: "B+R",
    source: "brouwer",
    moves: "pd dp cd qp op oq nq pq cn fq mp qn ic dj po qo cp cq bq co bp bo do bn dq ep dr cm jp cg ed qf qe pf nd pi oj oi nj mh gp gq dn dm fo hp ho eo en fn em el fm gn fl go ek dk dl cl eh di pj qi rf rg kd hn om re rd sf fi gk hm in hl ko kp gc df id jc ge dg cf ch bh dh bi hd he gd fd hc fe ec gh fc gi ii hk ik il im ij jl jj if km kl lj lk lo li kj ci cj mj nr mr lq lp mq np lr lm kh hg qc qd rc pc sd gg ce bd qb hi jg hj ob pb pa nb de ee gj hh ej nf mf me rk fh el nh ng lg lh mg og kg ni jh na ki mi ji nc mb od mc oc kr ms io ip jo jn ir hr ql rl qm rm ao bm ln kn mo be ae af ad ma la oa dd bg lb pn on er cr fp iq hq qj rj ks",
  },
  {
    id: "alphago-leesedol-3",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "Google DeepMind Challenge Match",
    round: "3",
    date: "2016-03-12",
    place: "Four Seasons Hotel, Seoul, Korea",
    black: "Lee Sedol",
    white: "AlphaGo",
    result: "W+R",
    source: "brouwer",
    moves: "pd pp cd dp cn fq id qf nc qm dj ed dc eg ef de df ce ec fd ff fc bd he ie hd ic hg if gg jh ci dg di ei bg bh be bi cj dh dk ej ck ch gi fh dm dn fg eh fm ek el gk ii cm fo en fl bk bj aj hm hj hi gj ji il jn cp cq dq dr bq eq pm pl qn om pn ql ol on rn oo ok qi ll hc qq qp rp pq rq qr rr ln qe re rd pe qd bb dd ee cb bc ad eb ba gb qk pk lo mn pj qj rl rk rm qk cr pf iq kq lq jq jo kn hr ip hp io jr kr ho gq hq in fn gn go gr gs fs is ib ks lr dq hn ds cq fp eo do ep er hs qh ph gs dq br hs pi oh gs bp hs co bo bn cp cs",
  },
  {
    id: "alphago-leesedol-4",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "Google DeepMind Challenge Match",
    round: "4",
    date: "2016-03-13",
    place: "Four Seasons Hotel, Seoul, South Korea",
    black: "AlphaGo",
    white: "Lee Sedol",
    result: "W+R",
    source: "brouwer",
    moves: "pd dp cd qp op oq nq pq cn fq mp po iq ec hd cg ed cj dc bp nc qi ep eo dk fp ck dj ej ei fi eh fh bj fk fg gg ff gf mc md lc nb id hc jg pj pi oj oi ni nh mh ng mg mi nj mf li ne nd mj lf mk me nf lh qj kk ik ji gh hj ge he fd fc ki jj lj kh jh ml nk ol ok pk pl qk nl kj ii rk om pg ql cp co oe rl sk rj hg ij km gi fj jl kl gl fl gm ch ee eb bg dg eg en fo df dh im hk bn if gd fe hf ih bh ci ho go or rg dn cq pr qr rf qg qf jc gr sf se sg rd bl bk ak cl hn in hp fr er es ds ah ai kd ie kc kb gk ib qh rh qs rs oh sl of sj ni nj oo jp",
  },
  {
    id: "alphago-leesedol-5",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "Google DeepMind Challenge Match",
    round: "5",
    date: "2016-03-15",
    place: "Four Seasons Hotel, Seoul, South Korea",
    black: "Lee Sedol",
    white: "AlphaGo",
    result: "W+R",
    source: "brouwer",
    moves: "qd dd pq dp oc po qo qn qp pm nq qe pe qf rd pf ql oe pl ol om ok nm qj rn gq cf fc bd ch dh di dg cc ci cj bi dj bh ml mm lm nl nk ln ll kn mn mo rm rl ro sn pn oo op no sm pp nc nb ob pb od pc mb oa mc gd gf gc fd ge ff hf hg if ig id jf jb jd jc je gh fb gg fe hc hi jl hb gb ga ib ha ia fa ka iq ii hh hj gi gj cn dq cq fq eq fp gp do co ep dr er dq gr fo eo fn hr in ir jq kr jr js kq lr lq mq mr nr ik fi fh jk ij jj il jm im eh fg mj lj li mi lk nj kj ei bk bj aj is hs so rn rk sl ai ah cl bl bm dm dn cm dl em en fl fj bn ak al fr mh ni lg ks ls bc bo bp og mf nh ph ce mk sg rg gl re se sf rf sh ld me ac ab ad cd bf kc kb oh nf lc bb cb aa gk hl hk jh kg lf kh lh le kf jg ao lj ki jn km sn on rp rq pk qm sf sd ma na ie he hq ms ko lp kp lo fs ks el fm hm am kk ne of de ap ee ed ke kd pd pg ng sk rn fk kl gm bm lk ck dk qk rj",
  },
  {
    id: "honinbo-title-hon-2025-1",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "80th Honinbo Title",
    round: "1",
    date: "2025-05-14",
    place: "Kofu, Yamanashi",
    black: "Shibano Toramaru",
    white: "Ichiriki Ryo",
    result: "W+R",
    source: "brouwer",
    moves: "pd dd pq dp fq qc qd pc od nb ql lp cn dn dm en co cp iq eq fp do np ck cc cd dc ed fb dl jo kn jn km ko lo mn ln mm jm im il hm jk dj cj dh fh fj hl gm gl fg gg eg fc gb gh fe gf ee ge fd ec eb gc gd hc hd ic ie kd jf lf hj jh lg kf jg kg ih gj gk ii ji kh hi gi fk ig ij if je hk ki li hf hg he hh eh ii em cm ih bc ii kj fi bb nc mb mj lj rc rb re sc rd oc nh qo qq qk rk pl rl pk nk qi rj on no oi ni og ng rg qh ph qg qf nf ri qj pj rn qn qm pm md ro",
  },
  {
    id: "honinbo-title-hon-2025-2",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "80th Honinbo Title",
    round: "2",
    date: "2025-05-25",
    place: "Noshiro, Akita",
    black: "Ichiriki Ryo",
    white: "Shibano Toramaru",
    result: "B+R",
    source: "brouwer",
    moves: "pd dp pq dc po nc oc nd pf jd de ce cf cd df fd he dj hc gd hd gb ge fe ff fg gf eg ef cn ld iq lb hh fi dh fm fk fq dq dm en em gp cm dn ci ej bj hl bn bo bl jg ji le me md ke lf kd kf je og pg oh ig ih jh oe hj ii ij jj jf kg lh pe qe qd qc rd rc kj li re qf rf rg pb pc rh sf ph sd hg if ik mf ql pj qi rl rm qk rk rj sl qj nj pl pm ol om nl lj mj mk mi nk ni oi oj mm ml ll nm nn mn lm on no sj ri ok lk qn qm rn sn so ro sm of se sn mo np sm mg lg sn nq mp sm ki kh sn sh sp si qr rq qq qp rr rp sq pr pn qo oo so bh ch ro gl gk so cj sr bi bp co ck aj ao dl ak bk cq cr bj cg br cp bq dr bs ap aq cl am bk lp dk lo mq lq lr kr nr ls mr kq ko kn jn ir jq hq jr hp io go",
  },
  {
    id: "honinbo-title-hon-2025-3",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "80th Honinbo Title",
    round: "3",
    date: "2025-06-06",
    place: "Moriguchi, Osaka",
    black: "Shibano Toramaru",
    white: "Ichiriki Ryo",
    result: "B+R",
    source: "brouwer",
    moves: "pd dp qp dd cq cp dq fq fr gr eq fp ep eo fo en bp bo bq go fn em gn ho hn io in jn jo hq ko jm hl pp po qq qo pq no mq mp lq jl dj pi im ip hp gk kl jk mn lp nn on op oo lk ml hj il mk km pj qi oi oh nh og ng of cn er kq nl oj nk li cc cd dc fc ec ed fb qc pc qd pb pe oe rf rb rh qg rg ri qb qa rc lg nj ra se qe re jg mf fd gc gb fe gd hc qf sb hd ic id jd je ie jc kd ib jf ke kf le lf me gj fk fj he if hf hg gf ff gg fg hh ek bd be bc ae lm qk ig nf ne kg kh lh rq rr sr rp sp sq jq jr rq qh ph sq fh eh rq pf pg sq ee",
  },
  {
    id: "honinbo-title-hon-2025-4",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "80th Honinbo Title",
    round: "4",
    date: "2025-06-18",
    place: "Toba, Mie",
    black: "Ichiriki Ryo",
    white: "Shibano Toramaru",
    result: "W+R",
    source: "brouwer",
    moves: "pd dp pq dc fq qo qm op pp po oo on no pm mp pk ce eq fp dn ed cd be ec fd gc cl hq jq go cq er co do bn qf pj oj qk qj pi ql pf pg qg pe of qe oe rg qh rh rk ri qd ph md cj ck dj rp ro ek cg fo fr ef ej fk fj hp iq ip jr kr cm bm jp kq gp gq io gr cp bp cn bo fn en ho em fm eo dl el cr dk bq gj eg fg df eh dg cc cb bc ff dd hb gg gf hg hf ee gi fi ei fh dh if bk bl bj ag bh he gk hj hk ij ik ir hr js hs dm jj hi lc ic ib mc jc oi qi ok pl jk ji hm il kk ig ih jg ge jh fe im lj nh lh jf lf mg lg mi li jd lb kb je ke ie kf ld kd kc bb ka lc aq br kc ac jb id bd rd rc re sq rb qb sc qc nj so rn ci ak ai ah bi bf af di gl gn fl kn sn sm sp rm mj kp lp ni lo nn ko jo km ln mn lm mm kl ll jm ml mf hd hc",
  },
  {
    id: "honinbo-title-hon-2025-5",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "80th Honinbo Title",
    round: "5",
    date: "2025-07-02",
    place: "Hakone, Kanagawa",
    black: "Ichiriki Ryo",
    white: "Shibano Toramaru",
    result: "B+2.5",
    source: "brouwer",
    moves: "qd dp cd pp nd ec df hc cq cp dq eq er fr fq ep gr dr fs cr nq oq np pn ql go ip ch ro qq dc ed bg ko in nn kq qj ol qg jc lc kd ld le ke je kf jf me lf kg lg lh nf ne oe md og od pe jg ig de ce ih hf hg if hh nc jb ib gf ge kb ic gd mb hb ha he lb jd id kc jd hd ia ie ga gb fa db fb fc ka eb ja mh mf oj bh pm rj qi qo po qk ri sj pl pk ok sl cj ci bj di dj ei jn io fp gp bc bq br fn hp gq fo bn bo jm km kl lq lr lp lm kn im mr kr nr pj oh oi ni pi ph nj nk mj mk lj lk kj jh ki kh dn fk ej ek dl dk gm bd be re rd hl gn ef dg kk jk ll jl mm co bp gj ij hk bm cm an bl cn jj eh gg fi ff fj hj ik ii hi fe fd bn si rm cn cl qf se sf sd ji il cc bn ee eg cn bk rg qe pg rf ng of re rh sh rf rk sk re mi nh rf qm rl re nl ln rf fh dh re rq rn qn rp sp qp sn ho hq rr rf fg gf re ml lm rf en em re bn rf am ii gl sq so gk hm ao do jp jq eo ad ac ae fl dd ea fm ls ks ms ds cs es ak bi ai ah aj al",
  },
  {
    id: "shusaku-126",
    variant: "go",
    size: 19,
    notation: "sgf",
    event: "Castle game, Osaka",
    round: null,
    date: "1846-09-11,14,15",
    place: null,
    black: "Yasuda Shusaku",
    white: "Inoue Gennan Inseki",
    result: "B+2",
    source: "brouwer",
    moves: "qd dc pq oc cp cf ep qo pe np po pp op qp oq oo pn qq nq on pm om pl mp mq ol pk lq lr kr lp kq qr rr rs mr nr pr ps qs no mo qr rm rl qs lo mn qr qm or ql qj rj ri rk ln mm qi rq jn ls ns gq go ck kc ic pc nj ke og oh pb qb ng mi mj nd ph qg pg hq hr ir iq hp jr fc lc ld mc lb mb md qf pf qh rg rh sh rf sg pj pi oi oj ni qk ok qe kb jb ka jc ob ja la db cc fe cn gr is fq io ji eb fb eg dj dk ej cj dh ij hm gj eh fl fg er dm fn dn gn jj jk kk ii ik jl kl il jh co do ih hn hl bl dg gh ch ig ec cr fd gd ed gc bk cm gs gp li kg in lj lg gm jf jg im fm kf lf mf le gf hf ff gg lk kj km lm ll jm ge he ef ea cb fr fs dr qa ra pa rb da gi fj fi fa ga gl ek em ho el en jo kn ci lh mh mg di ei lg qn rn re sl mg bm am lg eq es mg ha gb lg ds hs mg sj si lg sr sq mg hd hb lg ro so mg ss qs lg sn rp mg cl bn lg ml mk mg pj sf lg nn nl mg ib ia lg nc nb mg jd kd lg ma na mg qc rc lg js ks mg hc id lg fk hj mg hh hg lg gk hk mg ak lg al bm nf od ki ms kp ip jp lr oj mr ea sr",
  },
  {
    id: "woc-2025-kurita-takanashi-1",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 2025",
    round: "Between the two finalists",
    date: "2025",
    place: "Ankara, Türkiye",
    black: "Kurita Seiya",
    white: "Takanashi Yusuke",
    result: "49-15",
    source: "wthor",
    moves: "f5 d6 c3 d3 c4 f4 c5 b3 c2 d2 c6 b5 b4 b6 e3 a3 c1 e6 f3 e1 d1 b1 a5 f2 f1 g1 a4 e2 a2 g6 g5 h6 g4 h5 e7 e8 f6 d7 f8 f7 d8 c7 g3 h2 g8 g7 h8 h7 h4 g2 h3 a6 a7 b7 a8 b8 c8 b2 a1 h1",
  },
  {
    id: "woc-2025-kurita-takanashi-2",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 2025",
    round: "Between the two finalists",
    date: "2025",
    place: "Ankara, Türkiye",
    black: "Takanashi Yusuke",
    white: "Kurita Seiya",
    result: "31-33",
    source: "wthor",
    moves: "f5 d6 c3 d3 c4 f4 f6 f3 e6 e7 d7 g6 d8 c5 c6 c7 c8 f7 d2 b3 b4 e3 c2 c1 a4 f8 e1 b5 b6 a5 a6 e8 e2 b8 g3 f2 g5 g4 h4 h5 h7 h6 h3 h8 g7 b1 g8 b2 a8 a3 g2 h1 f1 g1 h2 d1 b7 a7 a2 a1",
  },
  {
    id: "woc-2019-takahashi-takanashi-1",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 2019",
    round: "Between the two finalists",
    date: "2019",
    place: "Prague, Czechia",
    black: "Takahashi Akihiro",
    white: "Takanashi Yusuke",
    result: "30-34",
    source: "wthor",
    moves: "f5 d6 c4 d3 c3 f4 f6 f3 e6 e7 c6 g6 e2 d7 f8 c5 e3 c7 d8 e8 f7 g5 b5 c8 b8 b4 b6 a5 a3 a4 a6 c2 d2 b3 a2 f1 e1 b7 d1 f2 b2 a1 g2 c1 b1 g3 h6 h7 h5 a7 h2 g8 h8 g4 a8 g7 h4 h3 g1 h1",
  },
  {
    id: "woc-2019-takahashi-takanashi-2",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 2019",
    round: "Between the two finalists",
    date: "2019",
    place: "Prague, Czechia",
    black: "Takanashi Yusuke",
    white: "Takahashi Akihiro",
    result: "32-32",
    source: "wthor",
    moves: "f5 f6 e6 f4 e3 c5 c4 d6 b5 d3 c3 e2 f3 g4 f1 d1 h4 g3 c6 g5 h5 g6 e1 g1 f2 h2 f7 d2 h3 h6 c7 d7 c1 b1 c2 b6 d8 e7 e8 a4 b4 b2 a5 a6 b3 a3 g7 f8 g8 h7 a7 b8 h8 a8 h1 g2 c8 b7 a1 a2",
  },
  {
    id: "woc-2019-takahashi-takanashi-3",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 2019",
    round: "Between the two finalists",
    date: "2019",
    place: "Prague, Czechia",
    black: "Takahashi Akihiro",
    white: "Takanashi Yusuke",
    result: "47-17",
    source: "wthor",
    moves: "f5 d6 c4 d3 c3 f4 f6 f3 e6 e7 c6 g6 g5 f7 e2 c7 d8 c5 b5 e8 f8 b3 d7 b6 e3 g3 a6 g4 c8 b7 a3 d2 e1 c2 b1 b8 b4 g7 h8 a4 a8 g8 f2 c1 d1 g1 b2 a1 f1 a7 a2 a5 h2 h3 h1 h7 h6 g2 h5 h4",
  },
  {
    id: "woc-2019-takahashi-takanashi-4",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 2019",
    round: "Between the two finalists",
    date: "2019",
    place: "Prague, Czechia",
    black: "Takahashi Akihiro",
    white: "Takanashi Yusuke",
    result: "35-29",
    source: "wthor",
    moves: "f5 d6 c4 d3 c3 f4 c5 b3 e2 e3 c2 d2 e6 e1 g4 d1 a3 c6 d7 f3 f2 h4 h3 h2 g3 h5 g5 g6 f6 h6 b6 f1 g2 f7 b4 b5 e7 a4 g8 h1 g1 c7 b8 d8 f8 a6 a5 a2 b7 g7 h8 a8 c8 e8 a7 h7 a1 b2 c1 b1",
  },
  {
    id: "woc-1997-suekuni-brightwell-1",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 1997",
    round: "Between the two finalists",
    date: "1997",
    place: "Athens, Greece",
    black: "Brightwell Graham",
    white: "Suekuni Makoto",
    result: "33-31",
    source: "wthor",
    moves: "f5 d6 c3 d3 c4 f4 c5 b3 c2 b4 c6 d2 e6 b5 a5 a6 a3 b6 a4 a2 e3 f3 g4 c1 f2 g3 d1 e2 e1 f1 h3 c7 d7 f7 f6 e8 b7 e7 b8 d8 f8 g5 g6 h6 c8 b2 h4 g7 h5 h2 h7 g2 a1 b1 a7 h8 g8 a8 g1 h1",
  },
  {
    id: "woc-1997-suekuni-brightwell-2",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 1997",
    round: "Between the two finalists",
    date: "1997",
    place: "Athens, Greece",
    black: "Brightwell Graham",
    white: "Suekuni Makoto",
    result: "29-35",
    source: "wthor",
    moves: "f5 d6 c3 d3 c4 f4 c5 b3 c2 e6 c6 b4 b5 d2 e3 a6 c1 b6 f3 f6 f7 e1 e2 f1 d1 f2 g1 g5 d7 g6 g4 e7 e8 d8 c8 f8 g8 c7 b8 h4 g3 h3 h5 b7 a8 a7 a3 a2 a4 a5 a1 b1 b2 h1 h2 h6 g7 h7 h8 g2",
  },
  {
    id: "woc-1997-suekuni-brightwell-3",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 1997",
    round: "Between the two finalists",
    date: "1997",
    place: "Athens, Greece",
    black: "Suekuni Makoto",
    white: "Brightwell Graham",
    result: "39-25",
    source: "wthor",
    moves: "f5 d6 c5 f4 e3 c6 d3 f6 e6 d7 g3 c4 b4 b3 b6 c3 b5 a3 a4 g4 c7 e2 d2 f2 f3 d1 c1 c2 h5 g5 h6 b1 d8 a5 e1 f1 f7 e7 a6 a7 b2 h3 h4 h7 g6 e8 c8 b7 a8 b8 g7 h8 f8 a1 a2 g1 h1 g8 g2 h2",
  },
  {
    id: "woc-1977-1",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 1977",
    round: "Between the two finalists",
    date: "1977",
    place: "Tokyo, Japan",
    black: "Inoue Hiroshi",
    white: "Heiberg Thomas",
    result: "34-30",
    source: "wthor",
    moves: "f5 d6 c3 f3 f4 d3 c4 g6 f6 e6 c5 c6 d7 d8 e7 g5 e3 d2 g4 h3 f7 b5 h5 g3 b4 b6 c8 b8 c7 e8 f8 g8 h4 h6 e2 d1 c1 a3 a6 a5 e1 f2 g7 c2 a4 h8 a2 b7 f1 b3 b1 b2 h7 a7 a8 a1 g1 g2 h2 h1",
  },
  {
    id: "woc-1977-4",
    variant: "reversi",
    size: 8,
    notation: "othello",
    event: "World Othello Championship 1977",
    round: "Between the two finalists",
    date: "1977",
    place: "Tokyo, Japan",
    black: "Inoue Hiroshi",
    white: "Heiberg Thomas",
    result: "45-19",
    source: "wthor",
    moves: "f5 d6 c5 f4 e3 c6 e6 f3 d3 f6 g4 c4 b4 a3 b5 e2 d2 h4 c7 b3 c3 a6 d7 d1 c1 c2 e7 b6 e1 f1 g1 f2 b1 c8 a5 a4 d8 e8 b7 a8 b8 b2 a1 a2 g5 h5 g3 h3 a7 g2 h1 h2 h6 g6 h7 g7 g8 h8 f8 f7",
  },
];
