import type { JourneyRole } from "./journeys.types";

/**
 * THE ROLES A PROJECTED SITE OF 1000 PLAYERS IS MADE OF.
 *
 * John, 2026-09-25: "an Artifact that explains and projects a site full of
 * 1000 users, and their XP vs IP journey. You would have people of all
 * abilities. The elite, the occasional player, the daily gamer, the full
 * participant, the only board games, the only Gomoku, the only word games,
 * the experimenter, etc... come up with 10-20 roles and get it to map out the
 * projected scores."
 *
 * Every number below is a modelling assumption, not a fact read from
 * anywhere real — there is no population of 1000 Itsutsu members to measure.
 * They are chosen to be *plausible* and to make the roles distinct from one
 * another in the way their names promise: an "Elite" who is not also the top
 * XP earner would be a broken model, not an interesting finding.
 *
 * `share` is players out of 1000, and **the eighteen rows sum to exactly
 * 1000** (`journeys.coverage`-style check in `journeys.test.ts`).
 *
 * Variants and puzzle kinds are a representative handful, not the whole
 * catalogue: `standard` (Gomoku), `renju`, `dropFour`, `reversi`, `checkers`,
 * `go`, `hex`, `tictactoe` for games, and `numberPlace`, `gomoji` for
 * puzzles. A role that "plays every family" is modelled as spreading its
 * games evenly across these eight rather than literally across all fifty-odd
 * `RuleVariant`s — enough to tell Board-Games-Only from Gomoku-Only from
 * Go-Player, which is the question this exists to answer.
 */
export const JOURNEY_ROLES: readonly JourneyRole[] = [
  {
    key: "elite",
    name: "Elite",
    description: "The top two percent by ability. Plays widely, chases the hardest puzzles, rarely misses a day.",
    share: 20,
    skill: { mean: 2200, spread: 100 },
    activeDaysPerMonth: 26,
    gamesPerActiveDay: 4,
    gameMix: [
      { variant: "standard", weight: 0.4 },
      { variant: "go", weight: 0.3 },
      { variant: "hex", weight: 0.15 },
      { variant: "checkers", weight: 0.15 },
    ],
    puzzlesPerActiveDay: 0.5,
    puzzleMix: [{ kind: "numberPlace", level: "hard", weight: 1 }],
    social: { buddiesPerMonth: 1, applausePerMonth: 2, challengesPerMonth: 2 },
    streakHabit: 0.9,
    churnPerMonth: 0.01,
  },
  {
    key: "risingTalent",
    name: "Rising Talent",
    description: "Improving quickly, and plays a broad mix of games while their rating climbs.",
    share: 50,
    skill: { mean: 1750, spread: 150 },
    activeDaysPerMonth: 20,
    gamesPerActiveDay: 3,
    gameMix: [
      { variant: "standard", weight: 0.5 },
      { variant: "reversi", weight: 0.25 },
      { variant: "dropFour", weight: 0.25 },
    ],
    puzzlesPerActiveDay: 0.3,
    puzzleMix: [
      { kind: "numberPlace", level: "medium", weight: 0.6 },
      { kind: "gomoji", level: "medium", weight: 0.4 },
    ],
    social: { buddiesPerMonth: 1, applausePerMonth: 3, challengesPerMonth: 3 },
    streakHabit: 0.7,
    churnPerMonth: 0.03,
  },
  {
    key: "dailyGamer",
    name: "Daily Gamer",
    description: "Logs in almost every day of the month for a couple of quick games.",
    share: 90,
    skill: { mean: 1600, spread: 120 },
    activeDaysPerMonth: 28,
    gamesPerActiveDay: 2,
    gameMix: [
      { variant: "standard", weight: 0.4 },
      { variant: "dropFour", weight: 0.3 },
      { variant: "tictactoe", weight: 0.3 },
    ],
    puzzlesPerActiveDay: 0.2,
    puzzleMix: [{ kind: "numberPlace", level: "easy", weight: 1 }],
    social: { buddiesPerMonth: 0.5, applausePerMonth: 2, challengesPerMonth: 1 },
    streakHabit: 0.85,
    churnPerMonth: 0.02,
  },
  {
    key: "weekendPlayer",
    name: "Weekend Player",
    description: "Only plays on Saturdays and Sundays, but plays several games each time.",
    share: 110,
    skill: { mean: 1580, spread: 130 },
    activeDaysPerMonth: 8,
    weekendOnly: true,
    gamesPerActiveDay: 3,
    gameMix: [
      { variant: "standard", weight: 0.5 },
      { variant: "reversi", weight: 0.5 },
    ],
    puzzlesPerActiveDay: 0.5,
    puzzleMix: [{ kind: "numberPlace", level: "medium", weight: 1 }],
    social: { buddiesPerMonth: 0.3, applausePerMonth: 1, challengesPerMonth: 1 },
    streakHabit: 0.5,
    churnPerMonth: 0.04,
  },
  {
    key: "occasional",
    name: "Occasional",
    description: "Drops in once or twice a month for a couple of games, and does not always come back.",
    share: 140,
    skill: { mean: 1600, spread: 150 },
    activeDaysPerMonth: 1.5,
    gamesPerActiveDay: 2,
    gameMix: [
      { variant: "standard", weight: 0.3 },
      { variant: "reversi", weight: 0.3 },
      { variant: "checkers", weight: 0.2 },
      { variant: "tictactoe", weight: 0.2 },
    ],
    puzzlesPerActiveDay: 0.2,
    puzzleMix: [{ kind: "numberPlace", level: "easy", weight: 1 }],
    social: { buddiesPerMonth: 0.1, applausePerMonth: 0.2, challengesPerMonth: 0.2 },
    streakHabit: 0,
    churnPerMonth: 0.08,
  },
  {
    key: "fullParticipant",
    name: "Full Participant",
    description: "Plays every family on the site, and is as active with buddies and applause as with games.",
    share: 50,
    skill: { mean: 1650, spread: 140 },
    activeDaysPerMonth: 24,
    gamesPerActiveDay: 3,
    gameMix: [
      { variant: "standard", weight: 0.125 },
      { variant: "renju", weight: 0.125 },
      { variant: "dropFour", weight: 0.125 },
      { variant: "reversi", weight: 0.125 },
      { variant: "checkers", weight: 0.125 },
      { variant: "go", weight: 0.125 },
      { variant: "hex", weight: 0.125 },
      { variant: "tictactoe", weight: 0.125 },
    ],
    puzzlesPerActiveDay: 0.6,
    puzzleMix: [
      { kind: "numberPlace", level: "medium", weight: 0.5 },
      { kind: "gomoji", level: "medium", weight: 0.5 },
    ],
    social: { buddiesPerMonth: 2, applausePerMonth: 4, challengesPerMonth: 3 },
    streakHabit: 0.8,
    churnPerMonth: 0.015,
  },
  {
    key: "boardGamesOnly",
    name: "Board Games Only",
    description: "Sticks to the stone-and-board games and never once opens a puzzle.",
    share: 60,
    skill: { mean: 1700, spread: 130 },
    activeDaysPerMonth: 18,
    gamesPerActiveDay: 3,
    gameMix: [
      { variant: "standard", weight: 0.3 },
      { variant: "reversi", weight: 0.3 },
      { variant: "checkers", weight: 0.2 },
      { variant: "go", weight: 0.1 },
      { variant: "hex", weight: 0.1 },
    ],
    puzzlesPerActiveDay: 0,
    puzzleMix: [],
    social: { buddiesPerMonth: 0.5, applausePerMonth: 1, challengesPerMonth: 1 },
    streakHabit: 0.6,
    churnPerMonth: 0.03,
  },
  {
    key: "gomokuOnly",
    name: "Gomoku Only",
    description: "Plays Gomoku, and Gomoku alone — every other family passed by.",
    share: 45,
    skill: { mean: 1650, spread: 150 },
    activeDaysPerMonth: 20,
    gamesPerActiveDay: 3,
    gameMix: [{ variant: "standard", weight: 1 }],
    puzzlesPerActiveDay: 0,
    puzzleMix: [],
    social: { buddiesPerMonth: 0.3, applausePerMonth: 0.5, challengesPerMonth: 0.5 },
    streakHabit: 0.65,
    churnPerMonth: 0.03,
  },
  {
    key: "reversiSpecialist",
    name: "Reversi Specialist",
    description: "Reversi, exclusively, climbing that one game's own ladder.",
    share: 35,
    skill: { mean: 1700, spread: 140 },
    activeDaysPerMonth: 18,
    gamesPerActiveDay: 3,
    gameMix: [{ variant: "reversi", weight: 1 }],
    puzzlesPerActiveDay: 0,
    puzzleMix: [],
    social: { buddiesPerMonth: 0.3, applausePerMonth: 0.5, challengesPerMonth: 0.5 },
    streakHabit: 0.6,
    churnPerMonth: 0.03,
  },
  {
    key: "draughtsPlayer",
    name: "Draughts Player",
    description: "Checkers and its cousins, rarely anything else.",
    share: 35,
    skill: { mean: 1680, spread: 140 },
    activeDaysPerMonth: 16,
    gamesPerActiveDay: 2,
    gameMix: [{ variant: "checkers", weight: 1 }],
    puzzlesPerActiveDay: 0,
    puzzleMix: [],
    social: { buddiesPerMonth: 0.3, applausePerMonth: 0.5, challengesPerMonth: 0.5 },
    streakHabit: 0.55,
    churnPerMonth: 0.035,
  },
  {
    key: "goPlayer",
    name: "Go Player",
    description: "Territory games only — mostly Go, played slowly and thoughtfully.",
    share: 25,
    skill: { mean: 1750, spread: 160 },
    activeDaysPerMonth: 14,
    gamesPerActiveDay: 2,
    gameMix: [{ variant: "go", weight: 1 }],
    puzzlesPerActiveDay: 0,
    puzzleMix: [],
    social: { buddiesPerMonth: 0.2, applausePerMonth: 0.5, challengesPerMonth: 0.3 },
    streakHabit: 0.5,
    churnPerMonth: 0.04,
  },
  {
    key: "wordGamesOnly",
    name: "Word Games Only",
    description: "Solves the word puzzle every day and never once plays a two-player game.",
    share: 55,
    skill: { mean: 1600, spread: 120 },
    activeDaysPerMonth: 20,
    gamesPerActiveDay: 0,
    gameMix: [],
    puzzlesPerActiveDay: 1.5,
    puzzleMix: [{ kind: "gomoji", level: "medium", weight: 1 }],
    social: { buddiesPerMonth: 0.2, applausePerMonth: 0.5, challengesPerMonth: 0 },
    streakHabit: 0.6,
    churnPerMonth: 0.03,
  },
  {
    key: "numbersSolver",
    name: "Numbers / Sudoku Solver",
    description: "A grid-puzzle regular, rarely playing a stone game against another person.",
    share: 65,
    skill: { mean: 1600, spread: 110 },
    activeDaysPerMonth: 22,
    gamesPerActiveDay: 0,
    gameMix: [],
    puzzlesPerActiveDay: 1.2,
    puzzleMix: [
      { kind: "numberPlace", level: "easy", weight: 0.3 },
      { kind: "numberPlace", level: "medium", weight: 0.5 },
      { kind: "numberPlace", level: "hard", weight: 0.2 },
    ],
    social: { buddiesPerMonth: 0.1, applausePerMonth: 0.3, challengesPerMonth: 0 },
    streakHabit: 0.75,
    churnPerMonth: 0.02,
  },
  {
    key: "experimenter",
    name: "Experimenter",
    description: "Tries every game and puzzle on the site, and rarely returns to the same one twice running.",
    share: 45,
    skill: { mean: 1600, spread: 180 },
    activeDaysPerMonth: 15,
    gamesPerActiveDay: 2,
    gameMix: [
      { variant: "standard", weight: 0.125 },
      { variant: "renju", weight: 0.125 },
      { variant: "dropFour", weight: 0.125 },
      { variant: "reversi", weight: 0.125 },
      { variant: "checkers", weight: 0.125 },
      { variant: "go", weight: 0.125 },
      { variant: "hex", weight: 0.125 },
      { variant: "tictactoe", weight: 0.125 },
    ],
    puzzlesPerActiveDay: 0.4,
    puzzleMix: [
      { kind: "numberPlace", level: "medium", weight: 0.5 },
      { kind: "gomoji", level: "medium", weight: 0.5 },
    ],
    social: { buddiesPerMonth: 0.4, applausePerMonth: 1, challengesPerMonth: 1 },
    streakHabit: 0.3,
    churnPerMonth: 0.05,
  },
  {
    key: "socialButterfly",
    name: "Social Butterfly",
    description: "More buddies, applause and game offers than games played — middling play, sociable everywhere else.",
    share: 55,
    skill: { mean: 1600, spread: 150 },
    activeDaysPerMonth: 22,
    gamesPerActiveDay: 1,
    gameMix: [
      { variant: "standard", weight: 0.5 },
      { variant: "reversi", weight: 0.5 },
    ],
    puzzlesPerActiveDay: 0.1,
    puzzleMix: [{ kind: "gomoji", level: "easy", weight: 1 }],
    social: { buddiesPerMonth: 4, applausePerMonth: 10, challengesPerMonth: 8 },
    streakHabit: 0.7,
    churnPerMonth: 0.025,
  },
  {
    key: "grinder",
    name: "Grinder",
    description: "Many short games a day — tic-tac-toe and Drop Four — volume over depth.",
    share: 45,
    skill: { mean: 1600, spread: 140 },
    activeDaysPerMonth: 25,
    gamesPerActiveDay: 6,
    gameMix: [
      { variant: "tictactoe", weight: 0.6 },
      { variant: "dropFour", weight: 0.4 },
    ],
    puzzlesPerActiveDay: 0,
    puzzleMix: [],
    social: { buddiesPerMonth: 0.2, applausePerMonth: 0.5, challengesPerMonth: 0.5 },
    streakHabit: 0.7,
    churnPerMonth: 0.03,
  },
  {
    key: "returningVeteran",
    name: "Returning Veteran",
    description: "Brought a record from another site on import, and plays only rarely here now.",
    share: 30,
    skill: { mean: 1750, spread: 160 },
    activeDaysPerMonth: 4,
    gamesPerActiveDay: 1,
    gameMix: [
      { variant: "standard", weight: 0.5 },
      { variant: "checkers", weight: 0.5 },
    ],
    puzzlesPerActiveDay: 0,
    puzzleMix: [],
    social: { buddiesPerMonth: 0.1, applausePerMonth: 0.2, challengesPerMonth: 0.1 },
    streakHabit: 0.2,
    churnPerMonth: 0.06,
    importedRecordApprox: true,
  },
  {
    key: "newcomer",
    name: "Newcomer",
    description: "Joins partway through the year, so their first months on every chart read zero.",
    share: 45,
    skill: { mean: 1600, spread: 150 },
    activeDaysPerMonth: 15,
    gamesPerActiveDay: 2,
    gameMix: [
      { variant: "standard", weight: 0.4 },
      { variant: "reversi", weight: 0.3 },
      { variant: "tictactoe", weight: 0.3 },
    ],
    puzzlesPerActiveDay: 0.3,
    puzzleMix: [{ kind: "numberPlace", level: "easy", weight: 1 }],
    social: { buddiesPerMonth: 1, applausePerMonth: 2, challengesPerMonth: 2 },
    streakHabit: 0.6,
    churnPerMonth: 0.03,
    joinMonth: 7,
  },
];

/** Sum of every role's share — must be exactly 1000; `journeys.test.ts` checks it. */
export const JOURNEY_TOTAL_PLAYERS = 1000;
