/**
 * TSUNAGI AT 4×4: 100 levels, easiest first.
 *
 * WRITTEN BY `node scripts/tsunagi-levels.ts`, NEVER BY HAND. Each line is
 * one level: its layout (a letter for each pair's two stones, `.` for an empty
 * cell) and its one answer (the letter of the line through every cell). Every
 * level is proved to have exactly one answer by `levels.test.ts`, and no two
 * are the same board under a turn or a mirror.
 */
export const TSUNAGI_4: readonly (readonly [string, string])[] = [
  [".ABCAD..D.BCE..E", "AABCADBCDDBCEEEE"],
  ["A.ABCD...CDBE..E", "AAABCDDBCCDBEEEE"],
  ["AB.C.DB...DCAE.E", "ABBCADBCADDCAEEE"],
  ["A..BCDA...EBCD.E", "AAABCDABCDEBCDEE"],
  ["ABC...DCAB..E.ED", "ABCCABDCABDDEEED"],
  [".AB...CBACD.E.ED", "AABBACCBACDDEEED"],
  ["AB.B.AC.DE...DEC", "ABBBAACCDEECDDEC"],
  ["A.B.CADB.E..C.ED", "AABBCADBCEDDCEED"],
  [".AB.ACDB...DCE.E", "AABBACDBCCDDCEEE"],
  ["A..AB..BC..CD..D", "AAAABBBBCCCCDDDD"],
  ["ABCD.....BC...AD", "ABCDABCDABCDAAAD"],
  ["A..B..CD....ABCD", "ABBBABCDABCDABCD"],
  ["ABC...D..B..AD.C", "ABCCABDCABDCADDC"],
  ["A.BCD.....B.DAC.", "AABCDABCDABCDACC"],
  ["A..ABC.C.D....BD", "AAAABCCCBDDDBBBD"],
  ["A..ABC....B.D.DC", "AAAABCCCBBBCDDDC"],
  ["A.BC..D.A...B.DC", "ABBCABDCABDCBBDC"],
  ["A..BCD....ABC..D", "AAABCDABCDABCDDD"],
  ["A.AB.CD.CE..E.DB", "AAABCCDBCEDBEEDB"],
  ["A.BC.BD.AD..C...", "ABBCABDCADDCCCCC"],
  ["A...B.C.DB...DCA", "AAAABBCADBCADDCA"],
  ["A..ABC.D.BC.D...", "AAAABCCDBBCDDDDD"],
  ["..ABAB..C.CDD...", "AAABABBBCCCDDDDD"],
  ["...AABCDB...C..D", "AAAAABCDBBCDCCCD"],
  ["A..ABCD...C...BD", "AAAABCDDBCCDBBBD"],
  ["ABC...B...ACD..D", "ABCCABBCAAACDDDD"],
  ["A.BC.BD..A..D..C", "ABBCABDCAADCDDDC"],
  ["A.ABC.D...B.C..D", "AAABCDDBCDBBCDDD"],
  ["A.ABCB...DE.C.DE", "AAABCBBBCDEECDDE"],
  ["....AB...CBACD.D", "AAAAABBACCBACDDD"],
  ["AB.C.A...DB.DC..", "ABBCAABCDDBCDCCC"],
  ["AB....A.CD...CDB", "ABBBAAABCDDBCCDB"],
  ["A.BCDA......DBC.", "AABCDABCDBBCDBCC"],
  ["A...BC.A.B.CD..D", "AAAABCCABBCCDDDD"],
  ["...ABCB.D.CA...D", "BBBABCBADCCADDDD"],
  ["A..B...C.BCD.AD.", "ABBBABCCABCDAADD"],
  [".ABC.B...DC.A..D", "AABCABBCADCCADDD"],
  [".A.B.B.C.C..AD.D", "AABBABBCACCCADDD"],
  ["A.B.C.A..B..CD.D", "AABBCAABCBBBCDDD"],
  ["...ABCB.D.C...DA", "BBBABCBADCCADDDA"],
  ["A..BCA.D.B....CD", "AABBCABDCBBDCCCD"],
  [".ABC....ABC.D..D", "AABCABBCABCCDDDD"],
  ["A..A...BCDC.D.B.", "AAAACCCBCDCBDDBB"],
  ["A.B.C.AB...CD..D", "AABBCAABCCCCDDDD"],
  ["A.BC..C.A...D.DB", "ABBCABCCABBBDDDB"],
  ["A.ABC.B.D.CD....", "AAABCCBBDCCDDDDD"],
  ["ABC...B.A.D.D.C.", "ABCCABBCADDCDDCC"],
  ["A...BC.A.D..B.DC", "AAAABCCABDCCBDDC"],
  [".AB.A.C.C.D.D..B", "AABBACCBCCDBDDDB"],
  [".ABCA...DBD....C", "AABCABBCDBDCDDDC"],
  ["ABC.....AD.CD..B", "ABCCABBCADBCDDBB"],
  ["A..B.BCDA...C.D.", "ABBBABCDACCDCCDD"],
  ["AB.B....CD.A.C.D", "ABBBAAAACDDACCDD"],
  ["A.B.C..B.DADC...", "AABBCAABCDADCDDD"],
  ["AB.C..B.D....DAC", "ABBCAABCDAACDDAC"],
  [".A.BA..C..C.BD.D", "AABBABBCBBCCBDDD"],
  ["...A.B.BAC..D.DC", "AAAAABBBACCCDDDC"],
  ["A..AB.BC.DC.DE.E", "AAAABBBCDDCCDEEE"],
  ["AB.B.C....A.C...", "ABBBACCCAAACCCCC"],
  ["..AB.B.....AC..C", "AAABABBBAAAACCCC"],
  ["...A.BC...DACB.D", "CCCACBCACBDACBDD"],
  ["...A.BC...BCAD.D", "AAAAABCCABBCADDD"],
  ["...A.BC.A.B.D.DC", "AAAAABCCABBCDDDC"],
  ["A.AB.CD..D....CB", "AAABCCDBCDDBCCCB"],
  ["AB...AC.C..BD..D", "ABBBAACBCCCBDDDD"],
  ["A..B.C..CD..D.AB", "AAABCCABCDABDDAB"],
  ["AB.B.AC...DCDE.E", "ABBBAACCDDDCDEEE"],
  ["A...BC...BC.A...", "AAAABCCABBCAAAAA"],
  ["A.BC..C....B...A", "ABBCABCCABBBAAAA"],
  [".ABC.B....A.C...", "AABCABBCAAACCCCC"],
  ["A..A.....B...CBC", "AAAACCCCCBBCCCBC"],
  ["...AABC.D.BC...D", "AAAAABCCDBBCDDDD"],
  ["...AAB.C.DB.DC..", "AAAAABBCDDBCDCCC"],
  [".ABCAB......CD.D", "AABCABBCCCCCCDDD"],
  ["A..B.CA..DB.C..D", "AAABCCABCDBBCDDD"],
  [".A.B.CBC.......A", "AABBACBCACCCAAAA"],
  [".AB..C...BC.A...", "AABBACCBABCBABBB"],
  ["A..BC.BA.......C", "AABBCABACAAACCCC"],
  ["AB.C....BA.....C", "ABBCAABCBABCBBBC"],
  ["A..B.CA..D.B.C.D", "AAABCCABCDDBCCDD"],
  ["...AABC.D..C.D.B", "AAAAABCCDBBCDDBB"],
  ["A...B.B.A...C..C", "AAAABBBAAAAACCCC"],
  ["A.BCBA.....CD..D", "AABCBABCBBBCDDDD"],
  ["A....BC..C....AB", "ABBBABCBACCBAAAB"],
  ["AB....CB.CD...AD", "ABBBACCBACDDAAAD"],
  ["...AA...BCDC.B.D", "AAAAACCCBCDCBBDD"],
  ["A..B.BC..D.C.A.D", "ABBBABCCADDCAADD"],
  ["A..A...BBC.CD..D", "AAAABBBBBCCCDDDD"],
  ["...AAB.B...CCD.D", "AAAAABBBCCCCCDDD"],
  ["A.....B.BA..C..C", "AAAABBBABAAACCCC"],
  ["A.AB.....CD.D.CB", "AAABDDDBDCDBDCCB"],
  ["..AB.B...C....AC", "AAABABBBACCCAAAC"],
  ["A..B.BC...D.ADC.", "ABBBABCCADDCADCC"],
  ["....A.B.CBC....A", "AAAAABBACBCACCCA"],
  ["A.AB..C..D...CDB", "AAABCCCBCDDBCCDB"],
  [".....A...BACC..B", "CCCCCAACCBACCBBB"],
  [".....A.B.C..B.CA", "BBBBBAABBCAABCCA"],
  ["AB.A...C.B.....C", "ABAAABACABACAAAC"],
  ["A..B..C...B..AC.", "ABBBABCCABBCAACC"],
  ["...A.B..C..AB..C", "CCCACBCACBCABBCC"],
];
